/* tslint:disable */
/* eslint-disable */
/**
 * 规范化接口演示
 * 让 .NET 开发更简单，更通用，更流行。
 *
 * OpenAPI spec version: 1.0.0
 * Contact: monksoul@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface BaseUnit
 */
export interface BaseUnit {
    /**
     * 
     * @type {boolean}
     * @memberof BaseUnit
     */
    isDeleted?: boolean | null;
    /**
     * 
     * @type {Date}
     * @memberof BaseUnit
     */
    deletedAt?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof BaseUnit
     */
    deletedBy?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof BaseUnit
     */
    createdAt?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof BaseUnit
     */
    createdBy?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof BaseUnit
     */
    updatedAt?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof BaseUnit
     */
    updatedBy?: number | null;
    /**
     * 
     * @type {string}
     * @memberof BaseUnit
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BaseUnit
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BaseUnit
     */
    baseUnitId?: number;
    /**
     * 
     * @type {string}
     * @memberof BaseUnit
     */
    code?: string | null;
}
