/* tslint:disable */
/* eslint-disable */
/**
 * 规范化接口演示
 * 让 .NET 开发更简单，更通用，更流行。
 *
 * OpenAPI spec version: 1.0.0
 * Contact: monksoul@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Item } from './item';
/**
 * 
 * @export
 * @interface Brand
 */
export interface Brand {
    /**
     * 
     * @type {boolean}
     * @memberof Brand
     */
    isDeleted?: boolean | null;
    /**
     * 
     * @type {Date}
     * @memberof Brand
     */
    deletedAt?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof Brand
     */
    deletedBy?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof Brand
     */
    createdAt?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof Brand
     */
    createdBy?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof Brand
     */
    updatedAt?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof Brand
     */
    updatedBy?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Brand
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Brand
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Brand
     */
    brandId?: number;
    /**
     * 
     * @type {Array<Item>}
     * @memberof Brand
     */
    items?: Array<Item> | null;
}
