/* tslint:disable */
/* eslint-disable */
/**
 * 规范化接口演示
 * 让 .NET 开发更简单，更通用，更流行。
 *
 * OpenAPI spec version: 1.0.0
 * Contact: monksoul@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CreateItemForSaleDto
 */
export interface CreateItemForSaleDto {
    /**
     * 
     * @type {string}
     * @memberof CreateItemForSaleDto
     */
    batchNumber?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof CreateItemForSaleDto
     */
    batchDate?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof CreateItemForSaleDto
     */
    quantity?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CreateItemForSaleDto
     */
    receivedQuantity?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CreateItemForSaleDto
     */
    unitCostNet?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CreateItemForSaleDto
     */
    unitPriceNet?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CreateItemForSaleDto
     */
    discount?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CreateItemForSaleDto
     */
    taxRate?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CreateItemForSaleDto
     */
    tax?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CreateItemForSaleDto
     */
    total?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CreateItemForSaleDto
     */
    orderId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CreateItemForSaleDto
     */
    itemOrderId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CreateItemForSaleDto
     */
    itemId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CreateItemForSaleDto
     */
    itemBatchId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CreateItemForSaleDto
     */
    unitCostId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CreateItemForSaleDto
     */
    unitPriceId?: number | null;
}
