/* tslint:disable */
/* eslint-disable */
/**
 * 规范化接口演示
 * 让 .NET 开发更简单，更通用，更流行。
 *
 * OpenAPI spec version: 1.0.0
 * Contact: monksoul@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CreateSupplierDto
 */
export interface CreateSupplierDto {
    /**
     * 
     * @type {string}
     * @memberof CreateSupplierDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSupplierDto
     */
    companyName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateSupplierDto
     */
    nit?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateSupplierDto
     */
    ci?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateSupplierDto
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateSupplierDto
     */
    phone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateSupplierDto
     */
    address?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateSupplierDto
     */
    city?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateSupplierDto
     */
    state?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateSupplierDto
     */
    country?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateSupplierDto
     */
    description?: string | null;
}
