/* tslint:disable */
/* eslint-disable */
/**
 * 规范化接口演示
 * 让 .NET 开发更简单，更通用，更流行。
 *
 * OpenAPI spec version: 1.0.0
 * Contact: monksoul@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CreateItemForSaleDto } from "./create-item-for-sale-dto"
/**
 *
 * @export
 * @interface CreateSaleDto
 */
export interface CreateSaleDto {
   /**
    *
    * @type {string}
    * @memberof CreateSaleDto
    */
   referenceNumber: string
   /**
    *
    * @type {number}
    * @memberof CreateSaleDto
    */
   itemsCount: number
   /**
    *
    * @type {number}
    * @memberof CreateSaleDto
    */
   totalQuantity: number
   /**
    *
    * @type {number}
    * @memberof CreateSaleDto
    */
   totalDiscount: number
   /**
    *
    * @type {number}
    * @memberof CreateSaleDto
    */
   totalTax: number
   /**
    *
    * @type {number}
    * @memberof CreateSaleDto
    */
   totalCost: number
   /**
    *
    * @type {number}
    * @memberof CreateSaleDto
    */
   orderTaxRate: number
   /**
    *
    * @type {number}
    * @memberof CreateSaleDto
    */
   orderTax: number
   /**
    *
    * @type {number}
    * @memberof CreateSaleDto
    */
   orderDiscount: number
   /**
    *
    * @type {number}
    * @memberof CreateSaleDto
    */
   grandTotal: number
   /**
    *
    * @type {string}
    * @memberof CreateSaleDto
    */
   status: string
   /**
    *
    * @type {string}
    * @memberof CreateSaleDto
    */
   note?: string | null
   /**
    *
    * @type {number}
    * @memberof CreateSaleDto
    */
   customerId: number
   /**
    *
    * @type {Array<CreateItemForSaleDto>}
    * @memberof CreateSaleDto
    */
   itemSales?: Array<CreateItemForSaleDto> | null
}
