/* tslint:disable */
/* eslint-disable */
/**
 * 规范化接口演示
 * 让 .NET 开发更简单，更通用，更流行。
 *
 * OpenAPI spec version: 1.0.0
 * Contact: monksoul@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CreateItemAdjustmentDto } from "./create-item-adjustment-dto"
/**
 *
 * @export
 * @interface CreateAdjustmentDto
 */
export interface CreateAdjustmentDto {
   /**
    *
    * @type {string}
    * @memberof CreateAdjustmentDto
    */
   referenceNumber: string
   /**
    *
    * @type {number}
    * @memberof CreateAdjustmentDto
    */
   itemsCount: number
   /**
    *
    * @type {number}
    * @memberof CreateAdjustmentDto
    */
   totalQuantity: number
   /**
    *
    * @type {string}
    * @memberof CreateAdjustmentDto
    */
   note?: string | null
   /**
    *
    * @type {Array<CreateItemAdjustmentDto>}
    * @memberof CreateAdjustmentDto
    */
   itemAdjustments: Array<CreateItemAdjustmentDto>
}
