/* tslint:disable */
/* eslint-disable */
/**
 * 规范化接口演示
 * 让 .NET 开发更简单，更通用，更流行。
 *
 * OpenAPI spec version: 1.0.0
 * Contact: monksoul@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SaleDto } from "./sale-dto"
/**
 *
 * @export
 * @interface CustomerDto
 */
export interface CustomerDto {
   /**
    *
    * @type {string}
    * @memberof CustomerDto
    */
   name?: string | null
   /**
    *
    * @type {string}
    * @memberof CustomerDto
    */
   description?: string | null
   /**
    *
    * @type {number}
    * @memberof CustomerDto
    */
   customerId?: number | null
   /**
    *
    * @type {string}
    * @memberof CustomerDto
    */
   companyName?: string | null
   /**
    *
    * @type {string}
    * @memberof CustomerDto
    */
   nit?: string | null
   /**
    *
    * @type {string}
    * @memberof CustomerDto
    */
   ci?: string | null
   /**
    *
    * @type {string}
    * @memberof CustomerDto
    */
   email?: string | null
   /**
    *
    * @type {string}
    * @memberof CustomerDto
    */
   phone?: string | null
   /**
    *
    * @type {string}
    * @memberof CustomerDto
    */
   address?: string | null
   /**
    *
    * @type {string}
    * @memberof CustomerDto
    */
   city?: string | null
   /**
    *
    * @type {string}
    * @memberof CustomerDto
    */
   state?: string | null
   /**
    *
    * @type {string}
    * @memberof CustomerDto
    */
   country?: string | null
   /**
    *
    * @type {Array<SaleDto>}
    * @memberof CustomerDto
    */
   sales?: Array<SaleDto> | null
}
