/* tslint:disable */
/* eslint-disable */
/**
 * 规范化接口演示
 * 让 .NET 开发更简单，更通用，更流行。
 *
 * OpenAPI spec version: 1.0.0
 * Contact: monksoul@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ItemAdjustmentDto } from "./item-adjustment-dto"
import { ItemDto } from "./item-dto"
import { ItemOrderDto } from "./item-order-dto"
import { ItemOrderReturnDto } from "./item-order-return-dto"
/**
 *
 * @export
 * @interface ItemBatchDto
 */
export interface ItemBatchDto {
   /**
    *
    * @type {boolean}
    * @memberof ItemBatchDto
    */
   isDeleted?: boolean | null
   /**
    *
    * @type {Date}
    * @memberof ItemBatchDto
    */
   deletedAt?: Date | null
   /**
    *
    * @type {number}
    * @memberof ItemBatchDto
    */
   deletedBy?: number | null
   /**
    *
    * @type {Date}
    * @memberof ItemBatchDto
    */
   createdAt?: Date | null
   /**
    *
    * @type {number}
    * @memberof ItemBatchDto
    */
   createdBy?: number | null
   /**
    *
    * @type {Date}
    * @memberof ItemBatchDto
    */
   updatedAt?: Date | null
   /**
    *
    * @type {number}
    * @memberof ItemBatchDto
    */
   updatedBy?: number | null
   /**
    *
    * @type {number}
    * @memberof ItemBatchDto
    */
   itemBatchId?: number
   /**
    *
    * @type {string}
    * @memberof ItemBatchDto
    */
   batchNumber?: string | null
   /**
    *
    * @type {Date}
    * @memberof ItemBatchDto
    */
   batchDate?: Date | null
   /**
    *
    * @type {number}
    * @memberof ItemBatchDto
    */
   quantity?: number | null
   /**
    *
    * @type {ItemDto}
    * @memberof ItemBatchDto
    */
   item?: ItemDto
   /**
    *
    * @type {Array<ItemAdjustmentDto>}
    * @memberof ItemBatchDto
    */
   itemAdjustments?: Array<ItemAdjustmentDto> | null
   /**
    *
    * @type {Array<ItemOrderDto>}
    * @memberof ItemBatchDto
    */
   itemOrders?: Array<ItemOrderDto> | null
   /**
    *
    * @type {Array<ItemOrderReturnDto>}
    * @memberof ItemBatchDto
    */
   itemOrderReturns?: Array<ItemOrderReturnDto> | null
}
