/* tslint:disable */
/* eslint-disable */
/**
 * 规范化接口演示
 * 让 .NET 开发更简单，更通用，更流行。
 *
 * OpenAPI spec version: 1.0.0
 * Contact: monksoul@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ItemBatchDto } from './item-batch-dto';
import { ItemDto } from './item-dto';
import { ItemOrder } from './item-order';
import { ItemSaleDto } from './item-sale-dto';
import { OrderDto } from './order-dto';
import { UnitDto } from './unit-dto';
/**
 * 
 * @export
 * @interface ItemForSaleDto
 */
export interface ItemForSaleDto {
    /**
     * 
     * @type {boolean}
     * @memberof ItemForSaleDto
     */
    isDeleted?: boolean | null;
    /**
     * 
     * @type {Date}
     * @memberof ItemForSaleDto
     */
    deletedAt?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof ItemForSaleDto
     */
    deletedBy?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof ItemForSaleDto
     */
    createdAt?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof ItemForSaleDto
     */
    createdBy?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof ItemForSaleDto
     */
    updatedAt?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof ItemForSaleDto
     */
    updatedBy?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ItemForSaleDto
     */
    itemForSaleId?: number;
    /**
     * 
     * @type {ItemOrder}
     * @memberof ItemForSaleDto
     */
    itemOrder?: ItemOrder;
    /**
     * 
     * @type {string}
     * @memberof ItemForSaleDto
     */
    batchNumber?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof ItemForSaleDto
     */
    batchDate?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof ItemForSaleDto
     */
    quantity?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ItemForSaleDto
     */
    receivedQuantity?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ItemForSaleDto
     */
    unitCostNet?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ItemForSaleDto
     */
    unitPriceNet?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ItemForSaleDto
     */
    discount?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ItemForSaleDto
     */
    taxRate?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ItemForSaleDto
     */
    tax?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ItemForSaleDto
     */
    total?: number | null;
    /**
     * 
     * @type {OrderDto}
     * @memberof ItemForSaleDto
     */
    order?: OrderDto;
    /**
     * 
     * @type {ItemDto}
     * @memberof ItemForSaleDto
     */
    item?: ItemDto;
    /**
     * 
     * @type {ItemBatchDto}
     * @memberof ItemForSaleDto
     */
    itemBatch?: ItemBatchDto;
    /**
     * 
     * @type {UnitDto}
     * @memberof ItemForSaleDto
     */
    unitCost?: UnitDto;
    /**
     * 
     * @type {UnitDto}
     * @memberof ItemForSaleDto
     */
    unitPrice?: UnitDto;
    /**
     * 
     * @type {Array<ItemSaleDto>}
     * @memberof ItemForSaleDto
     */
    itemSales?: Array<ItemSaleDto> | null;
}
