/* tslint:disable */
/* eslint-disable */
/**
 * 规范化接口演示
 * 让 .NET 开发更简单，更通用，更流行。
 *
 * OpenAPI spec version: 1.0.0
 * Contact: monksoul@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AdjustmentDto } from "./adjustment-dto"
import { ItemBatchDto } from "./item-batch-dto"
import { ItemDto } from "./item-dto"
/**
 *
 * @export
 * @interface ItemAdjustmentDto
 */
export interface ItemAdjustmentDto {
   /**
    *
    * @type {boolean}
    * @memberof ItemAdjustmentDto
    */
   isDeleted?: boolean | null
   /**
    *
    * @type {Date}
    * @memberof ItemAdjustmentDto
    */
   deletedAt?: Date | null
   /**
    *
    * @type {number}
    * @memberof ItemAdjustmentDto
    */
   deletedBy?: number | null
   /**
    *
    * @type {Date}
    * @memberof ItemAdjustmentDto
    */
   createdAt?: Date | null
   /**
    *
    * @type {number}
    * @memberof ItemAdjustmentDto
    */
   createdBy?: number | null
   /**
    *
    * @type {Date}
    * @memberof ItemAdjustmentDto
    */
   updatedAt?: Date | null
   /**
    *
    * @type {number}
    * @memberof ItemAdjustmentDto
    */
   updatedBy?: number | null
   /**
    *
    * @type {number}
    * @memberof ItemAdjustmentDto
    */
   itemAdjustmentId?: number
   /**
    *
    * @type {number}
    * @memberof ItemAdjustmentDto
    */
   quantity?: number | null
   /**
    *
    * @type {string}
    * @memberof ItemAdjustmentDto
    */
   action?: string | null
   /**
    *
    * @type {ItemDto}
    * @memberof ItemAdjustmentDto
    */
   item?: ItemDto
   /**
    *
    * @type {ItemBatchDto}
    * @memberof ItemAdjustmentDto
    */
   itemBatch?: ItemBatchDto
   /**
    *
    * @type {AdjustmentDto}
    * @memberof ItemAdjustmentDto
    */
   adjustment?: AdjustmentDto
}
