/* tslint:disable */
/* eslint-disable */
/**
 * 规范化接口演示
 * 让 .NET 开发更简单，更通用，更流行。
 *
 * OpenAPI spec version: 1.0.0
 * Contact: monksoul@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BrandSimpleDto } from "./brand-simple-dto"
import { CategoryItemSimpleDto } from "./category-item-simple-dto"
import { TaxSimpleDto } from "./tax-simple-dto"
import { UnitSimpleDto } from "./unit-simple-dto"
/**
 *
 * @export
 * @interface ItemSimpleDto
 */
export interface ItemSimpleDto {
   /**
    *
    * @type {string}
    * @memberof ItemSimpleDto
    */
   name?: string | null
   /**
    *
    * @type {string}
    * @memberof ItemSimpleDto
    */
   description?: string | null
   /**
    *
    * @type {number}
    * @memberof ItemSimpleDto
    */
   itemId?: number | null
   /**
    *
    * @type {string}
    * @memberof ItemSimpleDto
    */
   code?: string | null
   /**
    *
    * @type {number}
    * @memberof ItemSimpleDto
    */
   price?: number | null
   /**
    *
    * @type {number}
    * @memberof ItemSimpleDto
    */
   cost?: number | null
   /**
    *
    * @type {number}
    * @memberof ItemSimpleDto
    */
   quantity?: number | null
   /**
    *
    * @type {boolean}
    * @memberof ItemSimpleDto
    */
   isBatched?: boolean | null
   /**
    *
    * @type {string}
    * @memberof ItemSimpleDto
    */
   taxCostMethod?: string | null
   /**
    *
    * @type {string}
    * @memberof ItemSimpleDto
    */
   taxPriceMethod?: string | null
   /**
    *
    * @type {Array<CategoryItemSimpleDto>}
    * @memberof ItemSimpleDto
    */
   categoryItems?: Array<CategoryItemSimpleDto> | null
   /**
    *
    * @type {TaxSimpleDto}
    * @memberof ItemSimpleDto
    */
   taxCost?: TaxSimpleDto
   /**
    *
    * @type {TaxSimpleDto}
    * @memberof ItemSimpleDto
    */
   taxPrice?: TaxSimpleDto
   /**
    *
    * @type {BrandSimpleDto}
    * @memberof ItemSimpleDto
    */
   brand?: BrandSimpleDto
   /**
    *
    * @type {UnitSimpleDto}
    * @memberof ItemSimpleDto
    */
   unitPrice?: UnitSimpleDto
   /**
    *
    * @type {UnitSimpleDto}
    * @memberof ItemSimpleDto
    */
   unitCost?: UnitSimpleDto
}
