/* tslint:disable */
/* eslint-disable */
/**
 * 规范化接口演示
 * 让 .NET 开发更简单，更通用，更流行。
 *
 * OpenAPI spec version: 1.0.0
 * Contact: monksoul@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface MetaData
 */
export interface MetaData {
    /**
     * 
     * @type {number}
     * @memberof MetaData
     */
    currentPage?: number;
    /**
     * 
     * @type {number}
     * @memberof MetaData
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof MetaData
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof MetaData
     */
    totalCount?: number;
    /**
     * 
     * @type {boolean}
     * @memberof MetaData
     */
    hasPrevious?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MetaData
     */
    hasNext?: boolean;
}
