/* tslint:disable */
/* eslint-disable */
/**
 * 规范化接口演示
 * 让 .NET 开发更简单，更通用，更流行。
 *
 * OpenAPI spec version: 1.0.0
 * Contact: monksoul@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OrderDto } from './order-dto';
import { OrderReturnDto } from './order-return-dto';
/**
 * 
 * @export
 * @interface SupplierDto
 */
export interface SupplierDto {
    /**
     * 
     * @type {string}
     * @memberof SupplierDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SupplierDto
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof SupplierDto
     */
    supplierId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof SupplierDto
     */
    companyName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SupplierDto
     */
    nit?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SupplierDto
     */
    ci?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SupplierDto
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SupplierDto
     */
    phone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SupplierDto
     */
    address?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SupplierDto
     */
    city?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SupplierDto
     */
    state?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SupplierDto
     */
    country?: string | null;
    /**
     * 
     * @type {Array<OrderDto>}
     * @memberof SupplierDto
     */
    orders?: Array<OrderDto> | null;
    /**
     * 
     * @type {Array<OrderReturnDto>}
     * @memberof SupplierDto
     */
    orderReturns?: Array<OrderReturnDto> | null;
}
