/* tslint:disable */
/* eslint-disable */
/**
 * 规范化接口演示
 * 让 .NET 开发更简单，更通用，更流行。
 *
 * OpenAPI spec version: 1.0.0
 * Contact: monksoul@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UpdateBaseUnitDto
 */
export interface UpdateBaseUnitDto {
    /**
     * 
     * @type {boolean}
     * @memberof UpdateBaseUnitDto
     */
    isDeleted?: boolean | null;
    /**
     * 
     * @type {Date}
     * @memberof UpdateBaseUnitDto
     */
    deletedAt?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateBaseUnitDto
     */
    deletedBy?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof UpdateBaseUnitDto
     */
    createdAt?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateBaseUnitDto
     */
    createdBy?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof UpdateBaseUnitDto
     */
    updatedAt?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateBaseUnitDto
     */
    updatedBy?: number | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateBaseUnitDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateBaseUnitDto
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateBaseUnitDto
     */
    description?: string | null;
}
