/* tslint:disable */
/* eslint-disable */
/**
 * 规范化接口演示
 * 让 .NET 开发更简单，更通用，更流行。
 *
 * OpenAPI spec version: 1.0.0
 * Contact: monksoul@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface UpdateUnitDto
 */
export interface UpdateUnitDto {
   /**
    *
    * @type {string}
    * @memberof UpdateUnitDto
    */
   name: string
   /**
    *
    * @type {string}
    * @memberof UpdateUnitDto
    */
   code: string
   /**
    *
    * @type {string}
    * @memberof UpdateUnitDto
    */
   operation: string
   /**
    *
    * @type {number}
    * @memberof UpdateUnitDto
    */
   value: number
   /**
    *
    * @type {string}
    * @memberof UpdateUnitDto
    */
   description?: string | null
   /**
    *
    * @type {number}
    * @memberof UpdateUnitDto
    */
   baseUnitId?: number
}
